version: '3'
services:
  s-web:
    image: scjang/s-web:latest
    command: bash -c "service nginx start && cd /home/app/s && npm install --only=production && pm2-docker process.yml"
    ports:
      - "80:80"
    container_name: s-web
    environment:
      NODE_ENV: production
      PORT: 9000
    volumes:
      - /home/ubuntu/s-web:/home/app/s
      - /home/ubuntu/s-web/package.json:/home/app/s/package.json
      - /home/ubuntu/s-web/process.yml:/home/app/s/process.yml
      - /home/ubuntu/s-web/nginx.conf:/etc/nginx/conf.d/nginx.conf
